language: node_js
node_js:
  - '9'
cache:
  directories:
  - node_modules
before_deploy:
  - npm run build
deploy:
  - provider: npm
    skip-cleanup: true
    email: lkwilson96@gmail.com
    api_key: $NPMJS_TOKEN
    on:
      repo: larkwt96/puretone
      tags: true
  - provider: pages
    local-dir: build
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
