language: node_js
node_js:
  - "iojs"
  - "7"
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
    tags: true
    tag: next
